In [1]:
# Numpy
import numpy as np 

In [4]:
a=np.array([[1,2,3],[4,5,6]])

# type(a)
a.dtype

dtype('int64')

In [6]:
n=[[12,6],[7,8,9],[9,10,11,13]]
n

[[12, 6], [7, 8, 9], [9, 10, 11, 13]]

In [15]:
n=np.array([[1,2,3],[4,5,6]])
n
print(n)
n.shape
n.dtype
n.size
n.strides

[[1 2 3]
 [4 5 6]]


(24, 8)

In [16]:
print(a)

[[1 2 3]
 [4 5 6]]


In [17]:
# create a 5,5 array    
b=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
b



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
data={
    "maths":np.sum(a,axis=1),
    "avg": np.mean(a,axis=1),
    "Max": np.max(a,axis=1),
}
data

{'maths': array([ 6, 15]), 'avg': array([2., 5.]), 'Max': array([3, 6])}

In [20]:
a=np.array([[1,2,3],[4,5,6]])

In [21]:
a.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
import numpy as np

# 1. Create a 3D array with 9 elements
array3d = np.arange(1, 10).reshape(1, 3, 3)
print("3D array:\n", array3d)

# 2. Create a 2D array with 32 elements
array_2d = np.arange(1, 33).reshape(4, 8)
print("\n2D array:\n", array_2d)

# 3. Reshape the 2D array into two different shapes
reshaped_1 = array_2d.reshape(8, 4)
reshaped_2 = array_2d.reshape(2, 16)

print("\nReshaped to (8, 4):\n", reshaped_1)
print("\nReshaped to (2, 16):\n", reshaped_2)

# 4. Find the transpose
transposed_array = array_2d.T
print("\nTranspose:\n", transposed_array)

3D array:
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]

2D array:
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]]

Reshaped to (8, 4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]

Reshaped to (2, 16):
 [[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32]]

Transpose:
 [[ 1  9 17 25]
 [ 2 10 18 26]
 [ 3 11 19 27]
 [ 4 12 20 28]
 [ 5 13 21 29]
 [ 6 14 22 30]
 [ 7 15 23 31]
 [ 8 16 24 32]]
