In [1]:
# Numpy
import numpy as np 

In [4]:
a=np.array([[1,2,3],[4,5,6]])

# type(a)
a.dtype

dtype('int64')

In [6]:
n=[[12,6],[7,8,9],[9,10,11,13]]
n

[[12, 6], [7, 8, 9], [9, 10, 11, 13]]

In [15]:
n=np.array([[1,2,3],[4,5,6]])
n
print(n)
n.shape
n.dtype
n.size
n.strides

[[1 2 3]
 [4 5 6]]


(24, 8)

In [16]:
print(a)

[[1 2 3]
 [4 5 6]]


In [17]:
# create a 5,5 array    
b=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
b



array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
data={
    "maths":np.sum(a,axis=1),
    "avg": np.mean(a,axis=1),
    "Max": np.max(a,axis=1),
}
data

{'maths': array([ 6, 15]), 'avg': array([2., 5.]), 'Max': array([3, 6])}

In [20]:
a=np.array([[1,2,3],[4,5,6]])

In [21]:
a.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

SyntaxError: invalid syntax (2974209238.py, line 1)